name: Node.js CI

on:
  push:
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x, 20.x, 21.x, 22.x, 23.x]
        vite-version: [3, 4, 5, 6]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install vite ${{ matrix.vite-version }}
        run: npm i vite@${{ matrix.vite-version }}

      - name: Run tests for vite ${{ matrix.vite-version }}
        run: export NODE_OPTIONS=--openssl-legacy-provider && npm test
