name: Node.js CI

on:
  push:
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [22.x, 24.x, 26.x]
        vite-version: [6, 7, 8]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Install vite ${{ matrix.vite-version }}
        run: npm i vite@${{ matrix.vite-version }} --no-save

      - name: Run tests for vite ${{ matrix.vite-version }}
        run: npm test
